spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shareRecipe?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  address: localhost
  port: 8085
